# Creating the model with CO2 limit

in this notebook, the model created in model.ipynb will be imported and global_constraints of CO2 limit will be applied.

## Importing packages

In [3]:
import linopy
import pypsa

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd

import cartopy
import cartopy.crs as ccrs

import networkx as nx

import atlite
from atlite.gis import ExclusionContainer, shape_availability
from rasterio.plot import show
from rasterio.crs import CRS
import rasterio as rio

from pathlib import Path
import xarray as xr

## Importing the base model

In [4]:
n_no_co2 = pypsa.Network("pypsa_model_n.nc") # the model without CO2 limits is imported

INFO:pypsa.network.io:New version 1.0.7 available! (Current: 1.0.5)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, links, loads, storage_units, sub_networks

In [5]:
n_no_co2.global_constraints

Empty DataFrame
Columns: [type, investment_period, bus, carrier_attribute, sense, constant, mu]
Index: []

## Adding co2 limit constraint

In [6]:
n_no_co2.add(
    "GlobalConstraint",
    "CO2Limit",
    carrier_attribute="co2_emissions",
    sense="<=",
    constant=0, # the CO2 limit is 0 --> 100% renewable system
)

In [7]:
n_no_co2.global_constraints

,type,investment_period,bus,carrier_attribute,sense,constant,mu
name,,,,,,,
CO2Limit,primary_energy,NaN,,co2_emissions,<=,0.0,0.0

## Solving the model

In [11]:
# solve the model with co2 limit
n_no_co2.optimize(
    #snapshots=n_no_co2.snapshots[:168],  # 1 week
    solver_name="gurobi",
    log_to_console=False
)

INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.model:Solver options:
 - log_to_console: False
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 19/19 [00:03<00:00,  5.12it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 50.78it/s]
INFO:linopy.io: Writing time: 3.91s

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2750042

INFO:gurobipy:Set parameter LicenseID to value 2750042

Academic license - for non-commercial use only - expires 2026-12-04

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-12-04

Read LP format model from file /private/var/folders/h3/z_4l05b96rn0jmfgxq7ty0lw0000gn/T/linopy-problem-1p35qsj4.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/h3/z_4l05b96rn0jmfgxq7ty0lw0000gn/T/linopy-problem-1p35qsj4.lp

Reading time = 4.28 seconds

INFO:gurobipy:Reading time = 4.28 seconds

obj: 5019879 rows, 2193249 columns, 10762913 nonzeros

INFO:gurobipy:obj: 5019879 rows, 2193249 columns, 10762913 nonzeros

Set parameter LogToConsole to value 0

INFO:gurobipy:Set parameter LogToConsole to value 0
INFO:gurobipy:Gurobi Optimizer version 13.0.0 build v13.0.0rc1 (mac64[arm] - Darwin 25.2.0 25C56)
INFO:gurobipy:
INFO:gurobipy:CPU model: Apple M4 Pro
INFO:gurobipy:Thread count: 14 physical cores, 14 logical processors, using up to 14 threads
INFO:gurobipy:
INFO:gurobipy:Non-default parameters:
INFO:gurobipy:LogToConsole  0
INFO:gurobipy:
INFO:gurobipy:Optimize a model with 5019879 rows, 2193249 columns and 10762913 nonzeros (Min)
INFO:gurobipy:Model fingerprint: 0x32dd7df5
INFO:gurobipy:Model has 318609 linear objective coefficients
INFO:gurobipy:Coefficient statistics:
INFO:gurobipy:  Matrix range     [2e-10, 7e+02]
INFO:gurobipy:  Objective range  [1e-02, 2e+05]
INFO:gurobipy:  Bounds range     [0e+00, 0e+00]
INFO:gurobipy:  RHS range        [2e+00, 4e+05]
INFO:gurobipy:Warning: Model contains large matrix coefficient range
INFO:gurobipy:         Consider reformulating model or setting NumericFocus parameter
INFO:gurobipy:         to avoid numerical issues.
INFO:gurobipy:Presolve removed 2377884 rows and 152445 columns (presolve time = 8s)...
INFO:gurobipy:Presolve removed 2377884 rows and 152445 columns
INFO:gurobipy:Presolve time: 9.57s
INFO:gurobipy:Presolved: 2641995 rows, 2040804 columns, 8334785 nonzeros
INFO:gurobipy:
INFO:gurobipy:Concurrent LP optimizer: primal simplex, dual simplex, and barrier
INFO:gurobipy:Showing barrier log only...
INFO:gurobipy:
INFO:gurobipy:Ordering time: 9.51s
INFO:gurobipy:
INFO:gurobipy:Barrier statistics:
INFO:gurobipy: Dense cols : 329
INFO:gurobipy: AA' NZ     : 7.597e+06
INFO:gurobipy: Factor NZ  : 6.784e+07 (roughly 2.4 GB of memory)
INFO:gurobipy: Factor Ops : 2.394e+10 (less than 1 second per iteration)
INFO:gurobipy: Threads    : 12
INFO:gurobipy:
INFO:gurobipy:                  Objective                Residual
INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time
INFO:gurobipy:   0   6.21712958e+13 -7.89873585e+13  7.04e+05 5.03e+03  5.51e+11    21s
INFO:gurobipy:   1   8.12239363e+13 -8.44435688e+13  5.40e+05 4.02e+06  4.90e+11    22s
INFO:gurobipy:   2   8.14815228e+13 -2.32897633e+14  5.23e+05 3.34e+06  4.28e+11    22s
INFO:gurobipy:   3   7.72140915e+13 -4.05430739e+14  4.82e+05 2.26e+06  3.21e+11    23s
INFO:gurobipy:   4   4.55070233e+13 -1.11104189e+15  3.22e+05 1.07e+06  1.81e+11    23s
INFO:gurobipy:   5   2.40913138e+13 -1.35510084e+15  1.66e+05 4.41e+05  8.31e+10    24s
INFO:gurobipy:   6   1.17618801e+13 -1.38445458e+15  7.37e+04 1.66e+05  3.25e+10    25s
INFO:gurobipy:   7   8.00918821e+12 -1.28789233e+15  4.67e+04 8.08e+04  1.69e+10    25s
INFO:gurobipy:   8   6.34125368e+12 -1.12871818e+15  3.51e+04 4.06e+04  9.37e+09    26s
INFO:gurobipy:   9   5.19220813e+12 -1.06047106e+15  2.72e+04 3.03e+04  7.11e+09    26s
INFO:gurobipy:  10   4.48187874e+12 -1.02409154e+15  2.23e+04 2.63e+04  6.12e+09    27s
INFO:gurobipy:  11   3.68071868e+12 -9.55773947e+14  1.69e+04 1.83e+04  4.38e+09    27s
INFO:gurobipy:  12   2.89231959e+12 -8.86267473e+14  1.16e+04 1.14e+04  2.82e+09    28s
INFO:gurobipy:  13   2.45812534e+12 -7.78302325e+14  8.83e+03 6.94e+03  1.84e+09    28s
INFO:gurobipy:  14   2.01416811e+12 -6.94441760e+14  6.02e+03 4.76e+03  1.26e+09    29s
INFO:gurobipy:  15   1.72732789e+12 -5.67306621e+14  4.16e+03 2.44e+03  7.32e+08    30s
INFO:gurobipy:  16   1.38215672e+12 -4.43883376e+14  1.98e+03 1.45e+03  4.18e+08    31s
INFO:gurobipy:  17   1.27488767e+12 -1.54514072e+14  1.20e+03 3.10e+02  1.23e+08    31s
INFO:gurobipy:  18   1.20589590e+12 -5.83297525e+13  6.39e+02 6.86e+01  4.09e+07    31s
INFO:gurobipy:  19   1.16202236e+12 -1.64963868e+13  2.54e+02 8.47e+00  1.05e+07    32s
INFO:gurobipy:  20   1.02885000e+12 -5.14692381e+12  1.49e+01 1.58e+00  1.91e+06    32s
INFO:gurobipy:  21   8.84663735e+11 -2.92909000e+12  5.89e+00 9.23e-01  1.07e+06    33s
INFO:gurobipy:  22   8.22944460e+11 -2.85793976e+12  4.91e+00 9.01e-01  1.02e+06    33s
INFO:gurobipy:  23   8.10420305e+11 -2.75608776e+12  4.72e+00 8.70e-01  9.86e+05    34s
INFO:gurobipy:  24   7.79961055e+11 -2.63471476e+12  4.35e+00 8.32e-01  9.38e+05    34s
INFO:gurobipy:  25   7.05620746e+11 -1.99909614e+12  2.05e+01 6.42e-01  7.29e+05    35s
INFO:gurobipy:  26   6.06902367e+11 -1.39670160e+12  1.23e+01 4.71e-01  5.26e+05    36s
INFO:gurobipy:  27   4.42025726e+11 -6.35645875e+11  4.16e+00 2.47e-01  2.72e+05    36s
INFO:gurobipy:  28   3.60717338e+11 -4.03177391e+11  3.14e+00 1.63e-01  1.91e+05    37s
INFO:gurobipy:  29   2.59749120e+11 -2.04659436e+11  1.93e+00 9.07e-02  1.14e+05    38s
INFO:gurobipy:  30   2.04986346e+11 -1.11420480e+11  1.34e+00 5.69e-02  7.68e+04    38s
INFO:gurobipy:  31   1.44111960e+11 -5.69113758e+10  7.82e-01 4.37e-02  4.84e+04    39s
INFO:gurobipy:  32   1.30048017e+11 -2.04288539e+10  6.71e-01 1.65e-02  3.60e+04    39s
INFO:gurobipy:  33   1.12989665e+11  5.90783526e+08  5.50e-01 7.52e-03  2.67e+04    40s
INFO:gurobipy:  34   9.70233438e+10  7.79143491e+09  4.44e-01 3.75e-03  2.12e+04    40s
INFO:gurobipy:  35   7.95889636e+10  1.50715126e+10  3.30e-01 2.09e-03  1.53e+04    41s
INFO:gurobipy:  36   6.19992214e+10  2.02844513e+10  2.17e-01 8.11e-04  9.86e+03    41s
INFO:gurobipy:  37   6.06892713e+10  2.08537463e+10  2.09e-01 7.80e-04  9.41e+03    42s
INFO:gurobipy:  38   5.57022476e+10  2.16313142e+10  1.80e-01 8.13e-04  8.05e+03    42s
INFO:gurobipy:  39   4.60353462e+10  2.35620491e+10  1.21e-01 5.81e-04  5.31e+03    43s
INFO:gurobipy:  40   4.37274873e+10  2.48615932e+10  1.07e-01 3.58e-04  4.45e+03    44s
INFO:gurobipy:  41   4.04964991e+10  2.54918958e+10  8.52e-02 2.43e-04  3.54e+03    45s
INFO:gurobipy:  42   3.71206218e+10  2.58794701e+10  6.43e-02 1.87e-04  2.65e+03    46s
INFO:gurobipy:  43   3.63400906e+10  2.62395179e+10  5.93e-02 1.53e-04  2.38e+03    47s
INFO:gurobipy:  44   3.53730264e+10  2.65787229e+10  5.25e-02 1.22e-04  2.07e+03    48s
INFO:gurobipy:  45   3.50185054e+10  2.67749809e+10  4.99e-02 1.06e-04  1.94e+03    49s
INFO:gurobipy:  46   3.41723592e+10  2.69313641e+10  4.39e-02 9.00e-05  1.71e+03    50s
INFO:gurobipy:  47   3.34420587e+10  2.70668721e+10  3.87e-02 7.85e-05  1.50e+03    51s
INFO:gurobipy:  48   3.30918133e+10  2.72258709e+10  3.61e-02 6.65e-05  1.38e+03    52s
INFO:gurobipy:  49   3.25890181e+10  2.74680009e+10  3.24e-02 4.85e-05  1.21e+03    53s
INFO:gurobipy:  50   3.21576720e+10  2.76181361e+10  2.90e-02 4.18e-05  1.07e+03    54s
INFO:gurobipy:  51   3.16404652e+10  2.77226566e+10  2.51e-02 3.56e-05  9.24e+02    55s
INFO:gurobipy:  52   3.14726781e+10  2.77920876e+10  2.38e-02 3.04e-05  8.68e+02    55s
INFO:gurobipy:  53   3.13146506e+10  2.78705240e+10  2.25e-02 2.64e-05  8.12e+02    56s
INFO:gurobipy:  54   3.10091511e+10  2.79614667e+10  2.00e-02 2.23e-05  7.19e+02    57s
INFO:gurobipy:  55   3.09237835e+10  2.80536904e+10  1.93e-02 1.84e-05  6.77e+02    58s
INFO:gurobipy:  56   3.05694230e+10  2.81261583e+10  1.63e-02 1.56e-05  5.76e+02    59s
INFO:gurobipy:  57   3.04476435e+10  2.82115095e+10  1.52e-02 1.41e-05  5.27e+02    60s
INFO:gurobipy:  58   3.02774246e+10  2.82622589e+10  1.37e-02 1.24e-05  4.75e+02    61s
INFO:gurobipy:  59   3.02076807e+10  2.83161037e+10  1.31e-02 1.17e-05  4.46e+02    62s
INFO:gurobipy:  60   3.01179054e+10  2.83708482e+10  1.23e-02 1.10e-05  4.12e+02    64s
INFO:gurobipy:  61   3.00586811e+10  2.84183175e+10  1.17e-02 1.03e-05  3.87e+02    64s
INFO:gurobipy:  62   2.99678683e+10  2.84504040e+10  1.09e-02 9.30e-06  3.58e+02    65s
INFO:gurobipy:  63   2.99043514e+10  2.84982382e+10  1.03e-02 8.64e-06  3.32e+02    66s
INFO:gurobipy:  64   2.98587369e+10  2.85129843e+10  9.80e-03 8.16e-06  3.17e+02    67s
INFO:gurobipy:  65   2.97716823e+10  2.85522616e+10  8.96e-03 7.57e-06  2.88e+02    68s
INFO:gurobipy:  66   2.97436090e+10  2.85791867e+10  8.67e-03 6.71e-06  2.75e+02    69s
INFO:gurobipy:  67   2.96529481e+10  2.85955743e+10  7.71e-03 6.26e-06  2.49e+02    70s
INFO:gurobipy:  68   2.96362226e+10  2.86142552e+10  7.53e-03 5.77e-06  2.41e+02    71s
INFO:gurobipy:  69   2.95549253e+10  2.86452929e+10  6.65e-03 5.00e-06  2.14e+02    72s
INFO:gurobipy:  70   2.95128534e+10  2.86787967e+10  6.19e-03 4.59e-06  1.97e+02    73s
INFO:gurobipy:  71   2.94792932e+10  2.87000884e+10  5.82e-03 4.33e-06  1.84e+02    74s
INFO:gurobipy:  72   2.94570914e+10  2.87266396e+10  5.57e-03 4.00e-06  1.72e+02    75s
INFO:gurobipy:  73   2.94406095e+10  2.87457120e+10  5.37e-03 3.77e-06  1.64e+02    76s
INFO:gurobipy:  74   2.94276766e+10  2.87550691e+10  5.21e-03 3.56e-06  1.59e+02    76s
INFO:gurobipy:  75   2.93890822e+10  2.87762785e+10  4.74e-03 3.09e-06  1.45e+02    77s
INFO:gurobipy:  76   2.93725386e+10  2.87915441e+10  4.52e-03 2.91e-06  1.37e+02    78s
INFO:gurobipy:  77   2.93612172e+10  2.88032778e+10  4.39e-03 2.77e-06  1.32e+02    79s
INFO:gurobipy:  78   2.93458356e+10  2.88200951e+10  4.18e-03 2.57e-06  1.24e+02    80s
INFO:gurobipy:  79   2.93328628e+10  2.88313687e+10  4.01e-03 2.43e-06  1.18e+02    81s
INFO:gurobipy:  80   2.93267642e+10  2.88402016e+10  3.93e-03 2.33e-06  1.15e+02    82s
INFO:gurobipy:  81   2.93187618e+10  2.88482267e+10  3.83e-03 2.23e-06  1.11e+02    82s
INFO:gurobipy:  82   2.93091986e+10  2.88573308e+10  3.70e-03 2.12e-06  1.07e+02    83s
INFO:gurobipy:  83   2.92983962e+10  2.88669919e+10  3.56e-03 2.00e-06  1.02e+02    84s
INFO:gurobipy:  84   2.92933226e+10  2.88719092e+10  3.49e-03 1.89e-06  9.94e+01    85s
INFO:gurobipy:  85   2.92736308e+10  2.88835369e+10  3.23e-03 1.64e-06  9.20e+01    85s
INFO:gurobipy:  86   2.92645097e+10  2.88960404e+10  3.10e-03 1.51e-06  8.69e+01    86s
INFO:gurobipy:  87   2.92565032e+10  2.89059194e+10  2.99e-03 1.40e-06  8.27e+01    87s
INFO:gurobipy:  88   2.92309619e+10  2.89125725e+10  2.65e-03 1.27e-06  7.51e+01    88s
INFO:gurobipy:  89   2.92242394e+10  2.89250441e+10  2.57e-03 1.22e-06  7.06e+01    89s
INFO:gurobipy:  90   2.92109664e+10  2.89361554e+10  2.39e-03 1.40e-06  6.48e+01    90s
INFO:gurobipy:  91   2.91952937e+10  2.89433878e+10  2.19e-03 1.54e-06  5.94e+01    91s
INFO:gurobipy:  92   2.91917522e+10  2.89494754e+10  2.15e-03 1.63e-06  5.71e+01    91s
INFO:gurobipy:  93   2.91724860e+10  2.89555673e+10  1.89e-03 1.57e-06  5.12e+01    92s
INFO:gurobipy:  94   2.91598537e+10  2.89600812e+10  1.72e-03 1.57e-06  4.71e+01    93s
INFO:gurobipy:  95   2.91507025e+10  2.89682771e+10  1.59e-03 1.56e-06  4.30e+01    94s
INFO:gurobipy:  96   2.91441795e+10  2.89719299e+10  1.51e-03 1.49e-06  4.06e+01    95s
INFO:gurobipy:  97   2.91394307e+10  2.89762306e+10  1.45e-03 1.66e-06  3.85e+01    96s
INFO:gurobipy:  98   2.91338189e+10  2.89801676e+10  1.37e-03 1.57e-06  3.62e+01    96s
INFO:gurobipy:  99   2.91296022e+10  2.89848444e+10  1.32e-03 1.49e-06  3.41e+01    97s
INFO:gurobipy: 100   2.91250530e+10  2.89870602e+10  1.26e-03 1.42e-06  3.25e+01    98s
INFO:gurobipy: 101   2.91195032e+10  2.89899478e+10  1.18e-03 1.35e-06  3.06e+01    99s
INFO:gurobipy: 102   2.91115893e+10  2.89929546e+10  1.08e-03 1.43e-06  2.80e+01    99s
INFO:gurobipy: 103   2.91047402e+10  2.89969040e+10  9.93e-04 1.21e-06  2.54e+01   101s
INFO:gurobipy: 104   2.91008827e+10  2.89988256e+10  9.43e-04 1.28e-06  2.41e+01   101s
INFO:gurobipy: 105   2.90961573e+10  2.90001167e+10  8.80e-04 1.24e-06  2.26e+01   102s
INFO:gurobipy: 106   2.90879485e+10  2.90010079e+10  7.72e-04 1.14e-06  2.05e+01   103s
INFO:gurobipy: 107   2.90852153e+10  2.90047509e+10  7.37e-04 1.43e-06  1.90e+01   104s
INFO:gurobipy: 108   2.90821253e+10  2.90058080e+10  6.97e-04 1.34e-06  1.80e+01   104s
INFO:gurobipy: 109   2.90771845e+10  2.90090596e+10  6.35e-04 1.22e-06  1.61e+01   105s
INFO:gurobipy: 110   2.90748305e+10  2.90107303e+10  6.03e-04 1.63e-06  1.51e+01   106s
INFO:gurobipy: 111   2.90737418e+10  2.90117565e+10  5.89e-04 1.64e-06  1.46e+01   107s
INFO:gurobipy: 112   2.90704849e+10  2.90130663e+10  5.45e-04 1.96e-06  1.35e+01   107s
INFO:gurobipy: 113   2.90679268e+10  2.90143196e+10  5.10e-04 2.09e-06  1.26e+01   108s
INFO:gurobipy: 114   2.90649516e+10  2.90159044e+10  4.71e-04 2.15e-06  1.16e+01   109s
INFO:gurobipy: 115   2.90643833e+10  2.90167616e+10  4.63e-04 2.17e-06  1.12e+01   109s
INFO:gurobipy: 116   2.90641659e+10  2.90176245e+10  4.60e-04 2.73e-06  1.10e+01   110s
INFO:gurobipy: 117   2.90630236e+10  2.90187392e+10  4.44e-04 2.73e-06  1.04e+01   111s
INFO:gurobipy: 118   2.90615407e+10  2.90193256e+10  4.24e-04 2.80e-06  9.96e+00   112s
INFO:gurobipy: 119   2.90597832e+10  2.90202350e+10  4.01e-04 3.28e-06  9.33e+00   113s
INFO:gurobipy: 120   2.90566931e+10  2.90211535e+10  3.60e-04 3.09e-06  8.38e+00   114s
INFO:gurobipy: 121   2.90553854e+10  2.90223227e+10  3.42e-04 2.70e-06  7.80e+00   115s
INFO:gurobipy: 122   2.90539103e+10  2.90226106e+10  3.23e-04 2.62e-06  7.38e+00   115s
INFO:gurobipy: 123   2.90526896e+10  2.90228163e+10  3.06e-04 2.55e-06  7.05e+00   116s
INFO:gurobipy: 124   2.90515942e+10  2.90237715e+10  2.91e-04 2.21e-06  6.56e+00   117s
INFO:gurobipy: 125   2.90510267e+10  2.90239947e+10  2.83e-04 2.15e-06  6.38e+00   118s
INFO:gurobipy: 126   2.90493408e+10  2.90244111e+10  2.60e-04 2.03e-06  5.88e+00   119s
INFO:gurobipy: 127   2.90486816e+10  2.90246727e+10  2.50e-04 1.94e-06  5.66e+00   120s
INFO:gurobipy: 128   2.90467579e+10  2.90253561e+10  2.24e-04 1.67e-06  5.05e+00   121s
INFO:gurobipy: 129   2.90451735e+10  2.90257629e+10  2.02e-04 1.57e-06  4.58e+00   122s
INFO:gurobipy: 130   2.90445463e+10  2.90263934e+10  1.94e-04 1.40e-06  4.28e+00   123s
INFO:gurobipy: 131   2.90432673e+10  2.90268129e+10  1.77e-04 1.22e-06  3.88e+00   124s
INFO:gurobipy: 132   2.90424589e+10  2.90271481e+10  1.66e-04 1.11e-06  3.61e+00   125s
INFO:gurobipy: 133   2.90422487e+10  2.90272302e+10  1.62e-04 1.09e-06  3.54e+00   126s
INFO:gurobipy: 134   2.90415317e+10  2.90276333e+10  1.52e-04 9.79e-07  3.28e+00   127s
INFO:gurobipy: 135   2.90408114e+10  2.90279833e+10  1.42e-04 9.59e-07  3.03e+00   128s
INFO:gurobipy: 136   2.90399794e+10  2.90281383e+10  1.30e-04 9.06e-07  2.79e+00   129s
INFO:gurobipy: 137   2.90392654e+10  2.90285246e+10  1.20e-04 8.08e-07  2.53e+00   130s
INFO:gurobipy: 138   2.90389926e+10  2.90288308e+10  1.16e-04 7.16e-07  2.40e+00   131s
INFO:gurobipy: 139   2.90383422e+10  2.90290646e+10  1.06e-04 6.43e-07  2.19e+00   132s
INFO:gurobipy: 140   2.90377712e+10  2.90293736e+10  9.70e-05 5.81e-07  1.98e+00   133s
INFO:gurobipy: 141   2.90366073e+10  2.90296320e+10  7.85e-05 5.03e-07  1.65e+00   134s
INFO:gurobipy: 142   2.90362409e+10  2.90297808e+10  7.32e-05 4.74e-07  1.52e+00   135s
INFO:gurobipy: 143   2.90359791e+10  2.90299827e+10  6.92e-05 4.17e-07  1.41e+00   137s
INFO:gurobipy: 144   2.90357854e+10  2.90301690e+10  6.63e-05 3.80e-07  1.32e+00   138s
INFO:gurobipy: 145   2.90354351e+10  2.90303480e+10  6.08e-05 3.32e-07  1.20e+00   139s
INFO:gurobipy: 146   2.90351478e+10  2.90304568e+10  5.60e-05 3.09e-07  1.11e+00   140s
INFO:gurobipy: 147   2.90348733e+10  2.90305294e+10  5.13e-05 2.88e-07  1.02e+00   141s
INFO:gurobipy: 148   2.90345695e+10  2.90306134e+10  4.61e-05 2.71e-07  9.33e-01   142s
INFO:gurobipy: 149   2.90344728e+10  2.90307109e+10  4.44e-05 2.56e-07  8.87e-01   143s
INFO:gurobipy: 150   2.90342142e+10  2.90308241e+10  4.02e-05 2.24e-07  8.00e-01   144s
INFO:gurobipy: 151   2.90341066e+10  2.90308961e+10  3.84e-05 2.23e-07  7.57e-01   146s
INFO:gurobipy: 152   2.90340053e+10  2.90309614e+10  3.66e-05 2.00e-07  7.18e-01   147s
INFO:gurobipy: 153   2.90338646e+10  2.90310549e+10  3.44e-05 1.77e-07  6.63e-01   148s
INFO:gurobipy: 154   2.90337274e+10  2.90311584e+10  3.22e-05 1.52e-07  6.06e-01   149s
INFO:gurobipy: 155   2.90336175e+10  2.90311949e+10  3.03e-05 1.49e-07  5.71e-01   150s
INFO:gurobipy: 156   2.90335726e+10  2.90312259e+10  2.95e-05 1.42e-07  5.54e-01   151s
INFO:gurobipy: 157   2.90334447e+10  2.90312880e+10  2.74e-05 1.30e-07  5.09e-01   152s
INFO:gurobipy: 158   2.90333527e+10  2.90313205e+10  2.58e-05 1.26e-07  4.79e-01   154s
INFO:gurobipy: 159   2.90332349e+10  2.90313774e+10  2.38e-05 1.27e-07  4.38e-01   155s
INFO:gurobipy: 160   2.90331698e+10  2.90314448e+10  2.26e-05 9.59e-08  4.07e-01   156s
INFO:gurobipy: 161   2.90330767e+10  2.90314911e+10  2.10e-05 1.49e-07  3.74e-01   157s
INFO:gurobipy: 162   2.90330021e+10  2.90315258e+10  1.97e-05 8.20e-08  3.48e-01   158s
INFO:gurobipy: 163   2.90328749e+10  2.90315722e+10  1.75e-05 1.34e-07  3.07e-01   160s
INFO:gurobipy: 164   2.90328213e+10  2.90316033e+10  1.66e-05 5.68e-08  2.87e-01   161s
INFO:gurobipy: 165   2.90327105e+10  2.90316292e+10  1.47e-05 5.03e-08  2.55e-01   162s
INFO:gurobipy: 166   2.90326422e+10  2.90316496e+10  1.35e-05 5.12e-08  2.34e-01   163s
INFO:gurobipy: 167   2.90326138e+10  2.90316623e+10  1.29e-05 8.20e-08  2.24e-01   164s
INFO:gurobipy: 168   2.90325521e+10  2.90316818e+10  1.18e-05 1.34e-07  2.05e-01   165s
INFO:gurobipy: 169   2.90325022e+10  2.90317188e+10  1.09e-05 5.96e-08  1.85e-01   167s
INFO:gurobipy: 170   2.90324404e+10  2.90317376e+10  9.72e-06 6.33e-08  1.66e-01   168s
INFO:gurobipy: 171   2.90323893e+10  2.90317619e+10  8.80e-06 8.20e-08  1.48e-01   170s
INFO:gurobipy: 172   2.90323121e+10  2.90317751e+10  7.35e-06 5.22e-08  1.27e-01   171s
INFO:gurobipy: 173   2.90322885e+10  2.90317934e+10  6.91e-06 3.03e-08  1.17e-01   172s
INFO:gurobipy: 174   2.90322594e+10  2.90318015e+10  6.74e-06 9.31e-08  1.08e-01   174s
INFO:gurobipy: 175   2.90322239e+10  2.90318130e+10  8.65e-06 5.59e-08  9.70e-02   176s
INFO:gurobipy: 176   2.90321690e+10  2.90318232e+10  5.80e-06 4.47e-08  8.16e-02   178s
INFO:gurobipy: 177   2.90321513e+10  2.90318365e+10  5.39e-06 7.08e-08  7.43e-02   179s
INFO:gurobipy: 178   2.90321487e+10  2.90318407e+10  5.43e-06 1.04e-07  7.27e-02   180s
INFO:gurobipy: 179   2.90321202e+10  2.90318424e+10  6.99e-06 4.84e-08  6.55e-02   182s
INFO:gurobipy: 180   2.90320821e+10  2.90318508e+10  7.32e-06 4.47e-08  5.46e-02   184s
INFO:gurobipy: 181   2.90320781e+10  2.90318574e+10  8.02e-06 4.84e-08  5.21e-02   186s
INFO:gurobipy: 182   2.90320676e+10  2.90318608e+10  3.33e-05 5.22e-08  4.88e-02   189s
INFO:gurobipy: 183   2.90320359e+10  2.90318670e+10  2.63e-05 3.91e-08  3.98e-02   190s
INFO:gurobipy: 184   2.90320304e+10  2.90318692e+10  5.19e-04 2.38e-06  3.80e-02   191s
INFO:gurobipy: 185   2.90320244e+10  2.90318731e+10  4.95e-04 2.13e-06  3.57e-02   193s
INFO:gurobipy: 186   2.90320056e+10  2.90318775e+10  4.19e-04 6.03e-06  3.02e-02   194s
INFO:gurobipy: 187   2.90320037e+10  2.90318787e+10  4.11e-04 5.75e-06  2.95e-02   195s
INFO:gurobipy: 188   2.90319875e+10  2.90318804e+10  3.45e-04 5.33e-06  2.53e-02   197s
INFO:gurobipy: 189   2.90319839e+10  2.90318822e+10  3.30e-04 4.91e-06  2.40e-02   198s
INFO:gurobipy: 190   2.90319773e+10  2.90318882e+10  3.04e-04 3.51e-06  2.10e-02   199s
INFO:gurobipy: 191   2.90319593e+10  2.90318923e+10  2.31e-04 2.62e-06  1.58e-02   201s
INFO:gurobipy: 192   2.90319584e+10  2.90318935e+10  2.28e-04 1.83e-06  1.53e-02   201s
INFO:gurobipy: 193   2.90319479e+10  2.90318972e+10  1.84e-04 1.13e-06  1.20e-02   203s
INFO:gurobipy: 194   2.90319443e+10  2.90318983e+10  2.13e-04 1.57e-05  1.09e-02   204s
INFO:gurobipy: 195   2.90319321e+10  2.90318993e+10  1.52e-04 1.22e-05  7.75e-03   206s
INFO:gurobipy: 196   2.90319295e+10  2.90318997e+10  1.39e-04 1.09e-05  7.04e-03   207s
INFO:gurobipy: 197   2.90319229e+10  2.90319000e+10  1.05e-04 9.39e-06  5.38e-03   209s
INFO:gurobipy: 198   2.90319192e+10  2.90319005e+10  8.78e-05 7.71e-06  4.43e-03   211s
INFO:gurobipy: 199   2.90319176e+10  2.90319008e+10  8.96e-05 6.58e-06  3.96e-03   214s
INFO:gurobipy: 200   2.90319141e+10  2.90319017e+10  6.71e-05 2.64e-06  2.95e-03   216s
INFO:gurobipy: 201   2.90319133e+10  2.90319017e+10  4.42e-04 2.86e-06  2.75e-03   217s
INFO:gurobipy: 202   2.90319126e+10  2.90319020e+10  4.13e-04 1.66e-06  2.51e-03   218s
INFO:gurobipy: 203   2.90319098e+10  2.90319021e+10  2.38e-04 2.80e-06  1.81e-03   219s
INFO:gurobipy: 204   2.90319075e+10  2.90319023e+10  3.75e-04 1.83e-06  1.25e-03   220s

Interrupt request received

INFO:gurobipy:
INFO:gurobipy:
INFO:gurobipy:Stopped in 0 iterations and 702.38 seconds (1277.40 work units)
INFO:gurobipy:Solve interrupted
WARNING:linopy.constants:Optimization potentially failed:
Status: aborted
Termination condition: user_interrupt
Solution: 0 primals, 0 duals
Objective: nan
Solver model: available
Solver message: 11

('aborted', 'user_interrupt')

In [ ]:
n_no_co2.objective / 1e6 # in Mio. €

28497.756665749355

## Exporting the model into a .nc file

In [ ]:
n_no_co2.export_to_netcdf("pypsa_model_n_no_co2.nc")