# Creating the model with CO2 limit

in this notebook, the model created in model.ipynb will be imported and global_constraints of CO2 limit will be applied.

## Importing packages

In [11]:
import linopy
import pypsa

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd

import cartopy
import cartopy.crs as ccrs

import networkx as nx

import atlite
from atlite.gis import ExclusionContainer, shape_availability
from rasterio.plot import show
from rasterio.crs import CRS
import rasterio as rio

from pathlib import Path
import xarray as xr

## Importing the base model

In [12]:
n_no_co2 = pypsa.Network("pypsa_model_n.nc") # the model without CO2 limits is imported

INFO:pypsa.network.io:New version 1.0.7 available! (Current: 1.0.5)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, links, loads, storage_units, sub_networks

In [13]:
n_no_co2.global_constraints

Empty DataFrame
Columns: [type, investment_period, bus, carrier_attribute, sense, constant, mu]
Index: []

## Adding co2 limit constraint

In [14]:
n_no_co2.add(
    "GlobalConstraint",
    "CO2Limit",
    carrier_attribute="co2_emissions",
    sense="<=",
    constant=0, # the CO2 limit is 0 --> 100% renewable system
)

In [15]:
n_no_co2.global_constraints

,type,investment_period,bus,carrier_attribute,sense,constant,mu
name,,,,,,,
CO2Limit,primary_energy,NaN,,co2_emissions,<=,0.0,0.0

## Solving the model

In [16]:
# solve the model with co2 limit
n_no_co2.optimize(
    #snapshots=n_no_co2.snapshots[:168],  # 1 week
    solver_name="gurobi",
    method=2,
    crossover=0,
    BarConvTol=1.0e-05,
    AggFill=0,
    PreDual=0,
    GURO_PAR_BARDENSETHRESH=200,
    log_to_console=False
)

INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.model:Solver options:
 - method: 2
 - crossover: 0
 - BarConvTol: 1e-05
 - AggFill: 0
 - PreDual: 0
 - GURO_PAR_BARDENSETHRESH: 200
 - log_to_console: False
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 19/19 [00:03<00:00,  5.09it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 50.82it/s]
INFO:linopy.io: Writing time: 3.93s

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2750042

INFO:gurobipy:Set parameter LicenseID to value 2750042

Academic license - for non-commercial use only - expires 2026-12-04

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-12-04

Read LP format model from file /private/var/folders/h3/z_4l05b96rn0jmfgxq7ty0lw0000gn/T/linopy-problem-8_6jh9ze.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/h3/z_4l05b96rn0jmfgxq7ty0lw0000gn/T/linopy-problem-8_6jh9ze.lp

Reading time = 4.21 seconds

INFO:gurobipy:Reading time = 4.21 seconds

obj: 5019879 rows, 2193249 columns, 10762913 nonzeros

INFO:gurobipy:obj: 5019879 rows, 2193249 columns, 10762913 nonzeros

Set parameter Method to value 2

INFO:gurobipy:Set parameter Method to value 2

Set parameter Crossover to value 0

INFO:gurobipy:Set parameter Crossover to value 0

Set parameter BarConvTol to value 1e-05

INFO:gurobipy:Set parameter BarConvTol to value 1e-05

Set parameter AggFill to value 0

INFO:gurobipy:Set parameter AggFill to value 0

Set parameter PreDual to value 0

INFO:gurobipy:Set parameter PreDual to value 0

Set parameter GURO_PAR_BARDENSETHRESH to value 200

INFO:gurobipy:Set parameter GURO_PAR_BARDENSETHRESH to value 200

Set parameter LogToConsole to value 0

INFO:gurobipy:Set parameter LogToConsole to value 0
INFO:gurobipy:Gurobi Optimizer version 13.0.0 build v13.0.0rc1 (mac64[arm] - Darwin 25.2.0 25C56)
INFO:gurobipy:
INFO:gurobipy:CPU model: Apple M4 Pro
INFO:gurobipy:Thread count: 14 physical cores, 14 logical processors, using up to 14 threads
INFO:gurobipy:
INFO:gurobipy:Non-default parameters:
INFO:gurobipy:Method  2
INFO:gurobipy:BarConvTol  1e-05
INFO:gurobipy:Crossover  0
INFO:gurobipy:AggFill  0
INFO:gurobipy:PreDual  0
INFO:gurobipy:LogToConsole  0
INFO:gurobipy:GURO_PAR_BARDENSETHRESH  200
INFO:gurobipy:
INFO:gurobipy:Optimize a model with 5019879 rows, 2193249 columns and 10762913 nonzeros (Min)
INFO:gurobipy:Model fingerprint: 0x32dd7df5
INFO:gurobipy:Model has 318609 linear objective coefficients
INFO:gurobipy:Coefficient statistics:
INFO:gurobipy:  Matrix range     [2e-10, 7e+02]
INFO:gurobipy:  Objective range  [1e-02, 2e+05]
INFO:gurobipy:  Bounds range     [0e+00, 0e+00]
INFO:gurobipy:  RHS range        [2e+00, 4e+05]
INFO:gurobipy:Warning: Model contains large matrix coefficient range
INFO:gurobipy:         Consider reformulating model or setting NumericFocus parameter
INFO:gurobipy:         to avoid numerical issues.
INFO:gurobipy:Presolve removed 2161804 rows and 152445 columns
INFO:gurobipy:Presolve time: 4.41s
INFO:gurobipy:Presolved: 2858075 rows, 2040804 columns, 8334785 nonzeros
INFO:gurobipy:Elapsed ordering time = 5s
INFO:gurobipy:Ordering time: 9.22s
INFO:gurobipy:
INFO:gurobipy:Barrier statistics:
INFO:gurobipy: Dense cols : 329
INFO:gurobipy: Free vars  : 216080
INFO:gurobipy: AA' NZ     : 8.029e+06
INFO:gurobipy: Factor NZ  : 6.983e+07 (roughly 2.5 GB of memory)
INFO:gurobipy: Factor Ops : 2.493e+10 (less than 1 second per iteration)
INFO:gurobipy: Threads    : 14
INFO:gurobipy:
INFO:gurobipy:                  Objective                Residual
INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time
INFO:gurobipy:   0   1.95783208e+14 -9.31493402e+13  7.27e+05 2.93e+04  2.45e+12    15s
INFO:gurobipy:   1   2.29397603e+14 -2.61191219e+14  5.99e+05 5.76e+06  1.59e+12    16s
INFO:gurobipy:   2   2.41301059e+14 -1.55919244e+15  4.83e+05 2.37e+06  9.06e+11    16s
INFO:gurobipy:   3   1.13800329e+14 -2.02750815e+15  2.41e+05 1.09e+06  4.89e+11    17s
INFO:gurobipy:   4   8.55463918e+13 -2.12279511e+15  1.75e+05 6.25e+05  2.89e+11    18s
INFO:gurobipy:   5   5.90304601e+13 -2.20024111e+15  1.17e+05 3.69e+05  1.77e+11    18s
INFO:gurobipy:   6   4.15585781e+13 -2.24097639e+15  8.02e+04 1.71e+05  8.85e+10    19s
INFO:gurobipy:   7   2.95257732e+13 -2.18798352e+15  5.48e+04 9.16e+04  5.07e+10    19s
INFO:gurobipy:   8   2.13113071e+13 -2.14108866e+15  3.77e+04 7.13e+04  3.83e+10    20s
INFO:gurobipy:   9   1.96382114e+13 -2.12439559e+15  3.42e+04 6.08e+04  3.31e+10    20s
INFO:gurobipy:  10   1.64366470e+13 -2.13127989e+15  2.76e+04 4.78e+04  2.64e+10    21s
INFO:gurobipy:  11   1.56601174e+13 -2.12769695e+15  2.61e+04 4.41e+04  2.45e+10    21s
INFO:gurobipy:  12   1.20196418e+13 -2.08386169e+15  1.87e+04 3.07e+04  1.72e+10    22s
INFO:gurobipy:  13   1.04071129e+13 -1.94081921e+15  1.55e+04 1.88e+04  1.16e+10    23s
INFO:gurobipy:  14   8.88361868e+12 -1.79366802e+15  1.25e+04 1.09e+04  7.58e+09    24s
INFO:gurobipy:  15   8.46572711e+12 -1.71404723e+15  1.17e+04 9.04e+03  6.56e+09    24s
INFO:gurobipy:  16   7.38101901e+12 -1.62920089e+15  9.60e+03 6.21e+03  4.91e+09    25s
INFO:gurobipy:  17   7.21252084e+12 -1.61804327e+15  9.28e+03 5.95e+03  4.73e+09    26s
INFO:gurobipy:  18   6.60722104e+12 -1.51745356e+15  8.14e+03 4.81e+03  3.93e+09    26s
INFO:gurobipy:  19   5.67591588e+12 -1.43565464e+15  6.41e+03 3.78e+03  3.08e+09    27s
INFO:gurobipy:  20   4.94101149e+12 -1.29031862e+15  5.02e+03 2.67e+03  2.27e+09    28s
INFO:gurobipy:  21   4.42434245e+12 -1.12791346e+15  4.06e+03 1.83e+03  1.66e+09    29s
INFO:gurobipy:  22   3.74905205e+12 -1.00031677e+15  2.83e+03 1.33e+03  1.18e+09    30s
INFO:gurobipy:  23   3.33132097e+12 -7.66804220e+14  2.00e+03 7.05e+02  7.24e+08    30s
INFO:gurobipy:  24   3.06674864e+12 -5.52634578e+14  1.49e+03 3.65e+02  4.38e+08    31s
INFO:gurobipy:  25   2.67704004e+12 -2.70434863e+14  6.46e+02 1.00e+02  1.53e+08    32s
INFO:gurobipy:  26   2.54018667e+12 -3.32186415e+13  2.86e+02 3.17e+00  2.36e+07    32s
INFO:gurobipy:  27   2.00874362e+12 -8.94980062e+12  1.08e+02 1.97e-01  7.00e+06    33s
INFO:gurobipy:  28   1.20822089e+12 -4.61495006e+12  2.94e+01 2.28e-01  2.41e+06    33s
INFO:gurobipy:  29   8.97375752e+11 -3.28986899e+12  1.13e+01 1.93e-01  1.35e+06    34s
INFO:gurobipy:  30   8.56970095e+11 -3.28419722e+12  1.04e+01 1.91e-01  1.31e+06    34s
INFO:gurobipy:  31   7.79576636e+11 -3.06491146e+12  8.75e+00 1.78e-01  1.18e+06    35s
INFO:gurobipy:  32   7.54988441e+11 -2.96869815e+12  8.34e+00 1.71e-01  1.14e+06    35s
INFO:gurobipy:  33   7.09280841e+11 -2.59262665e+12  7.67e+00 1.48e-01  1.00e+06    35s
INFO:gurobipy:  34   6.62474388e+11 -2.22481551e+12  6.64e+00 1.28e-01  8.62e+05    36s
INFO:gurobipy:  35   6.39809577e+11 -1.82962385e+12  5.66e+00 1.20e-01  7.24e+05    36s
INFO:gurobipy:  36   6.28078195e+11 -1.74298608e+12  5.33e+00 1.24e-01  6.90e+05    37s
INFO:gurobipy:  37   5.81917954e+11 -1.48554383e+12  4.53e+00 1.49e-01  5.92e+05    37s
INFO:gurobipy:  38   4.35560577e+11 -9.61240860e+11  1.93e+00 1.91e-01  3.71e+05    38s
INFO:gurobipy:  39   4.12433354e+11 -9.09740116e+11  1.77e+00 1.88e-01  3.50e+05    38s
INFO:gurobipy:  40   3.37470668e+11 -6.71606883e+11  1.32e+00 1.29e-01  2.63e+05    39s
INFO:gurobipy:  41   2.41786689e+11 -4.64369227e+11  7.83e-01 7.97e-02  1.80e+05    40s
INFO:gurobipy:  42   1.91986877e+11 -2.14902252e+11  5.40e-01 8.97e-02  1.03e+05    41s
INFO:gurobipy:  43   1.26071752e+11 -7.28044763e+10  2.52e-01 1.18e-01  4.94e+04    41s
INFO:gurobipy:  44   1.19081521e+11 -4.94675565e+10  2.27e-01 9.59e-02  4.18e+04    42s
INFO:gurobipy:  45   1.07513832e+11 -2.81946620e+10  1.95e-01 7.70e-02  3.36e+04    42s
INFO:gurobipy:  46   9.49118800e+10 -1.48506985e+10  1.59e-01 6.33e-02  2.71e+04    43s
INFO:gurobipy:  47   9.23162746e+10 -3.41865408e+09  1.52e-01 4.90e-02  2.37e+04    43s
INFO:gurobipy:  48   8.18268558e+10  6.14949617e+09  1.26e-01 4.26e-02  1.87e+04    44s
INFO:gurobipy:  49   7.29515873e+10  1.19168001e+10  1.05e-01 5.00e-02  1.50e+04    44s
INFO:gurobipy:  50   6.62726533e+10  1.71722027e+10  8.86e-02 5.71e-02  1.21e+04    44s
INFO:gurobipy:  51   6.07053225e+10  2.02195397e+10  7.61e-02 5.08e-02  9.97e+03    45s
INFO:gurobipy:  52   5.18166533e+10  2.28176334e+10  5.52e-02 4.37e-02  7.13e+03    46s
INFO:gurobipy:  53   4.54208019e+10  2.44250579e+10  4.19e-02 4.02e-02  5.16e+03    46s
INFO:gurobipy:  54   4.26284336e+10  2.50963205e+10  3.53e-02 3.49e-02  4.31e+03    47s
INFO:gurobipy:  55   4.05701646e+10  2.55806979e+10  3.05e-02 3.11e-02  3.69e+03    48s
INFO:gurobipy:  56   3.87106849e+10  2.58887579e+10  2.66e-02 2.94e-02  3.15e+03    48s
INFO:gurobipy:  57   3.75849532e+10  2.62641319e+10  2.40e-02 2.85e-02  2.78e+03    49s
INFO:gurobipy:  58   3.64978952e+10  2.64135046e+10  2.13e-02 2.78e-02  2.48e+03    50s
INFO:gurobipy:  59   3.60519690e+10  2.66189753e+10  2.02e-02 2.64e-02  2.32e+03    51s
INFO:gurobipy:  60   3.54179028e+10  2.67706842e+10  1.86e-02 2.56e-02  2.13e+03    51s
INFO:gurobipy:  61   3.44903286e+10  2.70289969e+10  1.64e-02 2.46e-02  1.83e+03    52s
INFO:gurobipy:  62   3.37105472e+10  2.72745668e+10  1.43e-02 2.65e-02  1.58e+03    53s
INFO:gurobipy:  63   3.33619979e+10  2.73350904e+10  1.34e-02 2.71e-02  1.48e+03    54s
INFO:gurobipy:  64   3.26050185e+10  2.74571927e+10  1.14e-02 2.88e-02  1.27e+03    54s
INFO:gurobipy:  65   3.21145070e+10  2.75894830e+10  1.00e-02 2.94e-02  1.11e+03    55s
INFO:gurobipy:  66   3.18868259e+10  2.77355272e+10  9.40e-03 2.63e-02  1.02e+03    56s
INFO:gurobipy:  67   3.16425311e+10  2.78377346e+10  8.71e-03 2.73e-02  9.36e+02    57s
INFO:gurobipy:  68   3.14425762e+10  2.79789615e+10  8.17e-03 3.00e-02  8.52e+02    58s
INFO:gurobipy:  69   3.13053178e+10  2.80552820e+10  7.77e-03 3.01e-02  7.99e+02    58s
INFO:gurobipy:  70   3.09498027e+10  2.81450558e+10  6.72e-03 2.88e-02  6.90e+02    59s
INFO:gurobipy:  71   3.08951058e+10  2.81950023e+10  6.55e-03 2.67e-02  6.64e+02    60s
INFO:gurobipy:  72   3.07517690e+10  2.82536938e+10  6.13e-03 2.42e-02  6.15e+02    61s
INFO:gurobipy:  73   3.06117690e+10  2.83179515e+10  5.69e-03 2.15e-02  5.64e+02    62s
INFO:gurobipy:  74   3.04343892e+10  2.83796427e+10  5.14e-03 1.90e-02  5.05e+02    63s
INFO:gurobipy:  75   3.02815810e+10  2.84190547e+10  4.66e-03 1.74e-02  4.58e+02    64s
INFO:gurobipy:  76   3.01813554e+10  2.84598330e+10  4.33e-03 1.59e-02  4.24e+02    65s
INFO:gurobipy:  77   3.01240336e+10  2.85246285e+10  4.16e-03 1.42e-02  3.94e+02    65s
INFO:gurobipy:  78   3.00691597e+10  2.85591705e+10  3.97e-03 1.44e-02  3.72e+02    66s
INFO:gurobipy:  79   2.98922556e+10  2.85791312e+10  3.38e-03 1.45e-02  3.23e+02    67s
INFO:gurobipy:  80   2.98100726e+10  2.86159989e+10  3.10e-03 1.45e-02  2.94e+02    68s
INFO:gurobipy:  81   2.97280421e+10  2.86617621e+10  2.81e-03 1.48e-02  2.62e+02    69s
INFO:gurobipy:  82   2.96792885e+10  2.86907529e+10  2.63e-03 1.50e-02  2.43e+02    70s
INFO:gurobipy:  83   2.96623311e+10  2.87023515e+10  2.57e-03 1.52e-02  2.36e+02    70s
INFO:gurobipy:  84   2.96351992e+10  2.87230159e+10  2.46e-03 1.52e-02  2.24e+02    71s
INFO:gurobipy:  85   2.95953897e+10  2.87444356e+10  2.31e-03 1.51e-02  2.09e+02    72s
INFO:gurobipy:  86   2.95540144e+10  2.87616462e+10  2.15e-03 1.51e-02  1.95e+02    73s
INFO:gurobipy:  87   2.95261278e+10  2.87765319e+10  2.05e-03 1.49e-02  1.84e+02    74s
INFO:gurobipy:  88   2.95028431e+10  2.87978063e+10  1.95e-03 1.46e-02  1.73e+02    75s
INFO:gurobipy:  89   2.94816966e+10  2.88054978e+10  1.86e-03 1.44e-02  1.66e+02    76s
INFO:gurobipy:  90   2.94305257e+10  2.88210763e+10  1.65e-03 1.39e-02  1.50e+02    77s
INFO:gurobipy:  91   2.94033501e+10  2.88386350e+10  1.54e-03 1.29e-02  1.39e+02    78s
INFO:gurobipy:  92   2.93813420e+10  2.88578526e+10  1.45e-03 1.37e-02  1.29e+02    79s
INFO:gurobipy:  93   2.93659922e+10  2.88707489e+10  1.39e-03 1.45e-02  1.22e+02    80s
INFO:gurobipy:  94   2.93408004e+10  2.88846480e+10  1.28e-03 1.57e-02  1.12e+02    81s
INFO:gurobipy:  95   2.93335408e+10  2.88923777e+10  1.25e-03 1.65e-02  1.09e+02    82s
INFO:gurobipy:  96   2.93180843e+10  2.89020098e+10  1.19e-03 1.79e-02  1.02e+02    83s
INFO:gurobipy:  97   2.93013614e+10  2.89095301e+10  1.12e-03 1.90e-02  9.64e+01    84s
INFO:gurobipy:  98   2.92800931e+10  2.89203200e+10  1.03e-03 1.94e-02  8.85e+01    85s
INFO:gurobipy:  99   2.92732312e+10  2.89282617e+10  1.00e-03 1.86e-02  8.49e+01    86s
INFO:gurobipy: 100   2.92420052e+10  2.89388624e+10  8.74e-04 1.72e-02  7.46e+01    87s
INFO:gurobipy: 101   2.92291192e+10  2.89511987e+10  8.23e-04 1.51e-02  6.84e+01    88s
INFO:gurobipy: 102   2.92124740e+10  2.89574312e+10  7.57e-04 1.41e-02  6.28e+01    89s
INFO:gurobipy: 103   2.91988006e+10  2.89632998e+10  6.99e-04 1.30e-02  5.80e+01    90s
INFO:gurobipy: 104   2.91909384e+10  2.89681266e+10  6.66e-04 1.21e-02  5.48e+01    91s
INFO:gurobipy: 105   2.91841562e+10  2.89717768e+10  6.39e-04 1.15e-02  5.23e+01    92s
INFO:gurobipy: 106   2.91752745e+10  2.89768148e+10  6.03e-04 1.05e-02  4.88e+01    93s
INFO:gurobipy: 107   2.91648742e+10  2.89796194e+10  5.61e-04 9.99e-03  4.56e+01    94s
INFO:gurobipy: 108   2.91554474e+10  2.89836630e+10  5.21e-04 9.21e-03  4.23e+01    96s
INFO:gurobipy: 109   2.91469287e+10  2.89890611e+10  4.85e-04 8.21e-03  3.89e+01    97s
INFO:gurobipy: 110   2.91432205e+10  2.89897293e+10  4.70e-04 8.24e-03  3.78e+01    98s
INFO:gurobipy: 111   2.91359040e+10  2.89922397e+10  4.40e-04 8.50e-03  3.54e+01    99s
INFO:gurobipy: 112   2.91287284e+10  2.89959480e+10  4.11e-04 8.72e-03  3.27e+01   100s
INFO:gurobipy: 113   2.91266721e+10  2.89978905e+10  4.02e-04 8.77e-03  3.17e+01   101s
INFO:gurobipy: 114   2.91209406e+10  2.90022254e+10  3.81e-04 8.87e-03  2.92e+01   103s
INFO:gurobipy: 115   2.91096774e+10  2.90053496e+10  3.37e-04 9.22e-03  2.57e+01   103s
INFO:gurobipy: 116   2.91011639e+10  2.90069763e+10  3.01e-04 8.78e-03  2.32e+01   105s
INFO:gurobipy: 117   2.90980345e+10  2.90092025e+10  2.89e-04 8.06e-03  2.19e+01   106s
INFO:gurobipy: 118   2.90944192e+10  2.90112001e+10  2.75e-04 7.32e-03  2.05e+01   107s
INFO:gurobipy: 119   2.90890383e+10  2.90138349e+10  2.52e-04 6.32e-03  1.85e+01   108s
INFO:gurobipy: 120   2.90857570e+10  2.90151984e+10  2.39e-04 5.82e-03  1.74e+01   110s
INFO:gurobipy: 121   2.90818825e+10  2.90163899e+10  2.22e-04 5.37e-03  1.61e+01   111s
INFO:gurobipy: 122   2.90798818e+10  2.90172723e+10  2.14e-04 5.04e-03  1.54e+01   112s
INFO:gurobipy: 123   2.90772365e+10  2.90185764e+10  2.04e-04 4.55e-03  1.44e+01   113s
INFO:gurobipy: 124   2.90722499e+10  2.90191938e+10  1.82e-04 4.31e-03  1.31e+01   115s
INFO:gurobipy: 125   2.90702569e+10  2.90202389e+10  1.73e-04 3.90e-03  1.23e+01   115s
INFO:gurobipy: 126   2.90643865e+10  2.90207975e+10  1.48e-04 3.82e-03  1.07e+01   117s
INFO:gurobipy: 127   2.90612441e+10  2.90223658e+10  1.35e-04 3.94e-03  9.57e+00   118s
INFO:gurobipy: 128   2.90592956e+10  2.90234114e+10  1.26e-04 3.70e-03  8.84e+00   119s
INFO:gurobipy: 129   2.90573200e+10  2.90238722e+10  1.17e-04 3.62e-03  8.24e+00   120s
INFO:gurobipy: 130   2.90547999e+10  2.90243166e+10  1.06e-04 3.44e-03  7.51e+00   122s
INFO:gurobipy: 131   2.90533612e+10  2.90245907e+10  1.00e-04 3.29e-03  7.09e+00   123s
INFO:gurobipy: 132   2.90515360e+10  2.90253390e+10  9.20e-05 2.90e-03  6.45e+00   124s
INFO:gurobipy: 133   2.90500941e+10  2.90259740e+10  9.01e-05 2.60e-03  5.94e+00   125s
INFO:gurobipy: 134   2.90487306e+10  2.90265432e+10  9.90e-05 2.33e-03  5.46e+00   126s
INFO:gurobipy: 135   2.90483340e+10  2.90267632e+10  9.67e-05 2.22e-03  5.31e+00   128s
INFO:gurobipy: 136   2.90477028e+10  2.90269669e+10  9.32e-05 2.11e-03  5.11e+00   129s
INFO:gurobipy: 137   2.90461436e+10  2.90272368e+10  8.47e-05 1.97e-03  4.66e+00   131s
INFO:gurobipy: 138   2.90453721e+10  2.90275577e+10  8.06e-05 1.81e-03  4.39e+00   132s
INFO:gurobipy: 139   2.90444430e+10  2.90276866e+10  7.53e-05 1.74e-03  4.13e+00   133s
INFO:gurobipy: 140   2.90436604e+10  2.90279929e+10  7.09e-05 1.59e-03  3.86e+00   135s
INFO:gurobipy: 141   2.90423534e+10  2.90283698e+10  6.36e-05 1.39e-03  3.44e+00   137s
INFO:gurobipy: 142   2.90407804e+10  2.90286614e+10  5.62e-05 1.27e-03  2.98e+00   138s
INFO:gurobipy: 143   2.90396174e+10  2.90290555e+10  4.92e-05 1.10e-03  2.60e+00   140s
INFO:gurobipy: 144   2.90387120e+10  2.90294766e+10  4.36e-05 9.22e-04  2.27e+00   142s
INFO:gurobipy: 145   2.90382013e+10  2.90295840e+10  4.06e-05 8.74e-04  2.12e+00   144s
INFO:gurobipy: 146   2.90376094e+10  2.90299049e+10  3.69e-05 7.36e-04  1.90e+00   145s
INFO:gurobipy: 147   2.90370405e+10  2.90301422e+10  3.34e-05 6.44e-04  1.70e+00   147s
INFO:gurobipy: 148   2.90365419e+10  2.90302965e+10  3.02e-05 5.91e-04  1.54e+00   149s
INFO:gurobipy: 149   2.90360602e+10  2.90305532e+10  2.72e-05 4.89e-04  1.36e+00   151s
INFO:gurobipy: 150   2.90357738e+10  2.90306491e+10  2.54e-05 4.51e-04  1.26e+00   153s
INFO:gurobipy: 151   2.90353943e+10  2.90307576e+10  2.30e-05 4.12e-04  1.14e+00   154s
INFO:gurobipy: 152   2.90352197e+10  2.90309244e+10  2.18e-05 3.94e-04  1.06e+00   156s
INFO:gurobipy: 153   2.90348856e+10  2.90310218e+10  1.97e-05 3.79e-04  9.52e-01   158s
INFO:gurobipy: 154   2.90346372e+10  2.90310746e+10  1.81e-05 3.60e-04  8.78e-01   160s
INFO:gurobipy: 155   2.90344911e+10  2.90311278e+10  1.71e-05 3.70e-04  8.29e-01   162s
INFO:gurobipy: 156   2.90340188e+10  2.90311649e+10  1.41e-05 3.89e-04  7.03e-01   164s
INFO:gurobipy: 157   2.90338375e+10  2.90312328e+10  1.29e-05 4.22e-04  6.42e-01   166s
INFO:gurobipy: 158   2.90337361e+10  2.90312528e+10  1.22e-05 4.32e-04  6.12e-01   168s
INFO:gurobipy: 159   2.90335651e+10  2.90313566e+10  1.11e-05 4.39e-04  5.44e-01   170s
INFO:gurobipy: 160   2.90333635e+10  2.90314340e+10  9.79e-06 4.14e-04  4.75e-01   172s
INFO:gurobipy: 161   2.90332891e+10  2.90315195e+10  9.27e-06 4.14e-04  4.36e-01   174s
INFO:gurobipy: 162   2.90332043e+10  2.90315316e+10  8.74e-06 4.10e-04  4.12e-01   176s
INFO:gurobipy: 163   2.90329881e+10  2.90315793e+10  7.29e-06 3.90e-04  3.47e-01   178s
INFO:gurobipy: 164   2.90329106e+10  2.90316234e+10  6.79e-06 3.83e-04  3.17e-01   180s
INFO:gurobipy: 165   2.90328609e+10  2.90316523e+10  6.44e-06 4.41e-04  2.98e-01   182s
INFO:gurobipy: 166   2.90327286e+10  2.90316642e+10  5.55e-06 4.66e-04  2.62e-01   184s
INFO:gurobipy: 167   2.90326822e+10  2.90316970e+10  5.24e-06 5.23e-04  2.43e-01   186s
INFO:gurobipy: 168   2.90326212e+10  2.90317206e+10  4.84e-06 5.62e-04  2.22e-01   188s
INFO:gurobipy: 169   2.90325378e+10  2.90317314e+10  4.28e-06 5.82e-04  1.99e-01   190s
INFO:gurobipy: 170   2.90324997e+10  2.90317672e+10  4.03e-06 6.28e-04  1.80e-01   193s
INFO:gurobipy: 171   2.90324109e+10  2.90317781e+10  3.41e-06 6.25e-04  1.56e-01   195s
INFO:gurobipy: 172   2.90323729e+10  2.90318021e+10  3.16e-06 5.83e-04  1.41e-01   197s
INFO:gurobipy: 173   2.90322558e+10  2.90318126e+10  2.38e-06 5.10e-04  1.09e-01   200s
INFO:gurobipy: 174   2.90322129e+10  2.90318286e+10  2.08e-06 4.29e-04  9.46e-02   202s
INFO:gurobipy: 175   2.90321786e+10  2.90318412e+10  1.86e-06 3.59e-04  8.30e-02   205s
INFO:gurobipy: 176   2.90321473e+10  2.90318503e+10  2.00e-04 3.03e-04  7.30e-02   207s
INFO:gurobipy: 177   2.90321339e+10  2.90318547e+10  1.89e-04 2.80e-04  6.87e-02   208s
INFO:gurobipy:
INFO:gurobipy:Barrier solved model in 177 iterations and 208.43 seconds (531.02 work units)
INFO:gurobipy:Optimal objective 2.90321339e+10
INFO:gurobipy:
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 2193249 primals, 5019879 duals
Objective: 2.90e+10
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Generator-ext-p-lower, Generator-ext-p-upper, Link-ext-p-lower, Link-ext-p-upper, StorageUnit-ext-p_dispatch-lower, StorageUnit-ext-p_dispatch-upper, StorageUnit-ext-p_store-lower, StorageUnit-ext-p_store-upper, StorageUnit-ext-state_of_charge-lower, StorageUnit-ext-state_of_charge-upper, StorageUnit-energy_balance were not assigned to the network.

('ok', 'optimal')

In [17]:
n_no_co2.objective / 1e6 # in Mio. €

29032.13391567267

## Exporting the model into a .nc file

In [18]:
n_no_co2.export_to_netcdf("pypsa_model_n_no_co2.nc")

INFO:pypsa.network.io:Exported network 'Unnamed Network' saved to 'pypsa_model_n_no_co2.nc contains: carriers, buses, links, sub_networks, storage_units, global_constraints, loads, generators

<xarray.Dataset> Size: 27MB
Dimensions:                            (snapshots: 2920, carriers_i: 10,
                                        buses_i: 31, buses_t_p_i: 31,
                                        buses_t_marginal_price_i: 31,
                                        links_i: 74, links_t_p0_i: 74,
                                        links_t_p1_i: 74, sub_networks_i: 31,
                                        storage_units_i: 186,
                                        ...
                                        storage_units_t_state_of_charge_i: 186,
                                        global_constraints_i: 1, loads_i: 31,
                                        loads_t_p_set_i: 31, loads_t_p_i: 31,
                                        generators_i: 119,
                                        generators_t_p_max_pu_i: 69,
                                        generators_t_p_i: 80)
Coordinates: (12/21)
  * snapshots                          (snapshots) int64 23kB 0 1 ... 2918 2919
  * carriers_i                         (carriers_i) object 80B 'CCGT' ... 'el...
  * buses_i                            (buses_i) object 248B 'Alborz' ... 'Za...
  * buses_t_p_i                        (buses_t_p_i) object 248B 'Alborz' ......
  * buses_t_marginal_price_i           (buses_t_marginal_price_i) object 248B ...
  * links_i                            (links_i) object 592B 'line_Alborz__Ma...
    ...                                 ...
  * loads_i                            (loads_i) object 248B 'load_Alborz' .....
  * loads_t_p_set_i                    (loads_t_p_set_i) object 248B 'load_Al...
  * loads_t_p_i                        (loads_t_p_i) object 248B 'load_Alborz...
  * generators_i                       (generators_i) object 952B 'exist_CCGT...
  * generators_t_p_max_pu_i            (generators_t_p_max_pu_i) object 552B ...
  * generators_t_p_i                   (generators_t_p_i) object 640B 'exist_...
Data variables: (12/56)
    snapshots_snapshot                 (snapshots) datetime64[ns] 23kB 2025-0...
    snapshots_objective                (snapshots) float64 23kB 1.0 1.0 ... 1.0
    snapshots_stores                   (snapshots) float64 23kB 1.0 1.0 ... 1.0
    snapshots_generators               (snapshots) float64 23kB 1.0 1.0 ... 1.0
    carriers_co2_emissions             (carriers_i) float64 80B 0.198 ... 0.0
    carriers_color                     (carriers_i) object 80B 'red' ... 'black'
    ...                                 ...
    generators_marginal_cost           (generators_i) float64 952B 47.65 ... ...
    generators_capital_cost            (generators_i) float64 952B 1.079e+05 ...
    generators_efficiency              (generators_i) float64 952B 0.57 ... 1.0
    generators_p_nom_opt               (generators_i) float64 952B 997.0 ... ...
    generators_t_p_max_pu              (snapshots, generators_t_p_max_pu_i) float64 2MB ...
    generators_t_p                     (snapshots, generators_t_p_i) float64 2MB ...
Attributes:
    network__linearized_uc:       0
    network__multi_invest:        0
    network__objective:           29032133915.672672
    network__objective_constant:  0.0
    network_name:                 Unnamed Network
    network_pypsa_version:        1.0.5
    network_srid:                 4326
    crs:                          {"_crs": "GEOGCRS[\"WGS 84\",ENSEMBLE[\"Wor...
    meta:                         {}